@Library('global-shared-library')_

/* Pipeline */
pipeline {
  agent { label "gradleTests" }
  options { 
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }

  environment {
    HOME           = "${WORKSPACE}"
  }

  stages {
    stage ('CleanWs & checkout SCM') {
      steps {
        script {
          checkout scm
        }
      }
    }
    stage ('Preparation') {
      steps {
        script {
          env.GITHUB_ORGANIZATION   = github_organization.toLowerCase()
          env.GITHUB_REPO           = github_repo.toLowerCase()
        }
      }
    }

    stage('Gradle tests') {
        steps {
          container('gradle') {
            script {
                gradle.wrapper()
                gradle.clean()
                gradle.compileJava()
                gradle.test()
            }
          }
        }
    }

  }
}
