@Library('global-shared-library')_

/* Pipeline */
pipeline {
  agent { label "containerBuilds" }
  options { 
    // ansiColor('xterm') 
    disableConcurrentBuilds()
    skipDefaultCheckout true
  }

  environment {
    HOME           = "${WORKSPACE}"
  }

  stages {
    stage ('cleanWs & checkout scm') {
      steps {
        script {
          deleteDir()
          // cleanWs()
          checkout scm
        }
      }
    }
    stage ('preparation') {
      steps {
        script {
          env.DOCKERFILES           = dockerfiles
          env.GITHUB_ORGANIZATION   = github_organization.toLowerCase()
          // env.SYSTEM                = system.toLowerCase()
          env.GITHUB_REPO           = github_repo.toLowerCase()
          env.DOCKER_USERNAME       = docker_username.toLowerCase()
        }
      }
    }
    stage('Build, push and deploy') {
        when {
            allOf {
            expression { dockerfiles }
            branch "main"
            }
        }
        steps {
          container('maven') {
            script {
                mavenInstall.install()
                mavenInstall.test()
            }
          }
          container('docker') {
            script {
                dockerBuild.login()
                dockerBuild.build(env.DOCKER_USERNAME + "/" + env.GITHUB_REPO + ":" + env.BUILD_NUMBER)
                dockerBuild.push(env.DOCKER_USERNAME + "/" + env.GITHUB_REPO + ":" + env.BUILD_NUMBER)
            }
          }
        }
    }

    stage ('Update values') {
      steps {
        script {
          git branch: 'main', url: "https://github.com/tomasferrarisenda/omniman-service-helm-chart.git"
          sh 'ls'
          sh 'tree'
          updateValues.updateDev(tag: env.BUILD_NUMBER)
          gitCommit.commitAndPush(email: "tomas.ferrari@sendati.com", organization: env.GITHUB_ORGANIZATION, service: env.GITHUB_REPO)
        }
      }
    }
  }
  // post { 
  //   always {
  //     script {
  //       cleanWs()
  //     }
  //   }
  // }
}
